version: "2"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile4deploy
    container_name: best-api-web
    working_dir: /etc/nginx/
    tty: true
    stdin_open: true
    ports:
      - 2017:2017
    depends_on: 
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile4deploy
    container_name: best-api-server
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - 2018:2018
    depends_on: 
      - db
  db:
    image: mongo:3
    container_name: best-api-db
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
    ports:
      - 27001:27017