#  生产环境
version: "2"
services:
  api-web:
    image: yalishizhude/bestapi-web
    container_name: api-web
    tty: true
    stdin_open: true
    restart: always
    network_mode: host
    depends_on:
      - api-server
  api-server:
    image: yalishizhude/bestapi-server
    container_name: api-server
    tty: true
    stdin_open: true
    restart: always
    network_mode: host
    depends_on: 
      - api-db
  api-db:
    image: mongo:3
    container_name: api-db
    restart: always
    network_mode: host
    volumes:
      - ./data:/data