# 离线构建版本,减少pull镜像时间
version: "2"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: api-web
    working_dir: /etc/nginx/
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 2017:2017
    depends_on: 
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api-server
    working_dir: /app
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 2018:2018
    depends_on: 
      - db
  db:
    image: mongo:3
    container_name: api-db
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 27001:27017