version: "3"
services:
  web:
    build:
      context: ./web
    container_name: api-web
    working_dir: /app
    tty: true
    stdin_open: true
    volumes: 
      - api_web_modules:/app/node_modules
      - ./web:/app
    ports:
      - 2017:2017
    command: npm run compose
  server:
    build:
      context: ./server
    container_name: api-server
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - api_server_modules:/app/node_modules
      - ./server:/app
    ports:
      - 2018:2018
      - 8102:8012
    command: npm run compose
    depends_on: 
      - db
  db:
    image: mongo:latest
    container_name: api-db
    ports:
      - 27018:27017
volumes:
  api_web_modules:
  api_server_modules: