/* node modules */
declare module 'process'
declare module 'crypto'
declare module 'fs'
declare module 'path'
declare module 'events'

/* 3rd modules */
declare module 'koa'
declare module 'koa-better-body'
declare module 'koa-router'
declare module 'mongoose'
declare module 'sinon'
declare module 'ava'
declare module 'path-to-regexp'
declare module 'lodash'
declare module 'jsonwebtoken'
declare module 'ajv'
declare module 'underscore'
declare module 'axios'
declare module 'json-schema-faker'